apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: opencart
  name: opencart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opencart
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: opencart
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: OPENCART_DATABASE_HOST
              value: mariadb
            - name: OPENCART_DATABASE_NAME
              value: bitnami_opencart
            - name: OPENCART_DATABASE_PORT_NUMBER
              value: "3306"
            - name: OPENCART_DATABASE_USER
              value: bn_opencart
            - name: OPENCART_HOST
              value: localhost:8080
          image: docker.io/bitnami/opencart:3
          name: opencart
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/opencart
              name: opencart-opencart-data
            - mountPath: /bitnami/opencart_storage/
              name: opencart-opencart-storage-data
      restartPolicy: Always
      volumes:
        - name: opencart-opencart-data
          persistentVolumeClaim:
            claimName: opencart-opencart-data
        - name: opencart-opencart-storage-data
          persistentVolumeClaim:
            claimName: opencart-opencart-storage-data
status: {}
